dist: trusty
sudo: required
language: node_js
node_js:
  - "7.10"
os:
  - linux

before_install:
  # Install yarn.
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn config set spin false
  - yarn config set progress false
  # Global Dependencies
  - yarn global add firebase-tools
  # Run chrome on travis
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=chromium-browser
  - echo "--no-sandbox" > ~/.config/chromium-flags.conf
install:
  - yarn

script:
  - yarn run lint
  - yarn run test:ci

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then yarn run build:prod; fi
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then firebase deploy --token $FIREBASE_TOKEN; fi
