dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
os:
  - linux
before_install:
    # Run chrome on travis
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - export CHROME_BIN=chromium-browser
    - echo "--no-sandbox" > ~/.config/chromium-flags.conf
    # Update npm
    # - npm install -g npm
    # - npm config set spin false
    # - npm config set progress false
install:
    - npm install
    # Fixed cannot find module 'reflect-metadata'
    # - npm install reflect-metadata
script:
    - npm test -- --single-run   